sudo: required
language: python
python:
  - "2.7"
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo apt-get update
  - sudo apt-get install ffmpeg
# Install packages
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib seaborn pytest nose
- pip install pysal
- pip install python-coveralls
- pip install pytest-mpl
- pip install pytest-cov
- py.test --version
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: py.test --mpl-baseline-path=tests/baseline_images --mpl --cov=parse_files --cov=visualizations --cov=utils --cov=environment_file --cov=transform_data
after_success:
  - coveralls
