from distutils.core import setup

setup(name='avidaspatial',
      version='1.01',
      description="Tools for working with spatial data generated by the Avida Digital Evolution platform",
      author="Emily Dolson",
      author_email="EmilyLDolson@gmail.com",
      url="https://github.com/emilydolson/avida-spatial-tools",
      packages=["avidaspatial"],
      keywords = ["avida"],
      download_url = "https://github.com/emilydolson/avida-spatial-tools/tarball/1.01",
      )
